### PR TITLE
Add Heroku setup

### PR DESCRIPTION
**Pull request by chiragrank**
Have set up the Heroku on my account as of now. we can move it to a neutral account later on as suggested in the meeting.
The app is available at [Mental health dashboard](https://mental-health-dashboard.herokuapp.com/)

### CODE REVIEW

**Comment by chiragrank** [comment]
@fatse did you push directly into the main branch or I made some mistake?
Are all the packages listed in the force pushed update in this pull request needed to be mentioned in the requirements.txt?

**Comment by fatse** [comment]
@chiragrank I see this PR just now, sorry about that.

I created [this issue](https://github.com/UBC-MDS/Mental-Health-in-Tech-Dashboard/issues/23) regarding the deployment to Heroku. Do we still want to merge this PR?

**Comment by chiragrank** [comment]
@fatse No issues, just a misunderstanding that I didn’t expect the commit directly in the main branch which lead to the conflict and duplication.  Thanks for adding that issue with the information.

For the merging thing, there is not much-added extra by the pull request except the requirements.txt.  the current one in the main branch has more packages. The one in the pull request is created based on the required imports in the files with another method being the use of `pip freeze`. Can you please elaborate on the method of generating the requirements.txt  in the main branch?  We can cancel this pull request if we prefer the requirements.txt currently in the main branch

**Comment by fatse** [comment]
Sure, I generated `requirements.txt` using the usual `pip freeze > requirements.txt` command and so it contains only the libraries that we used in our `apps.py` except for `gunicorn` server which we need for Heroku.

**Pull request closed without merging**
