### PR TITLE
Added data with selected features

### PR DESCRIPTION
**Pull request by chiragrank**

### CODE REVIEW

**Comment by d-sel** [comment]
@chiragrank:
1. Can we move the processing.ipynb file to `src` directory?
2. I think some of the column names are still showing up as questions rather than the specified variables. I believe total number of features should be 30 (i.e.: we're dropping the rest from 63). Anything that didn't have a variable name specified should be dropped.

**Comment by chiragrank** [comment]
yes, we can do that. yes, you are right. Thanks for catching it. I made a minor mistake in that. get back with the update within few minutes

**Comment by chiragrank** [comment]
@d-sel Can you have a look now?

**Review by mikelynch416 — APPROVED** [review]
Looks good Chirag!
edit: Actually I think we still need to `git rm Processing.ipynb`

**Comment by chiragrank** [comment]
@mikelynch416  Updated it. Very sorry for these delays

**Comment by d-sel** [comment]
@chiragrank , this is great. 

One last thing: I noticed the `read_csv` lines should be updated for the relative path since you've moved the file. From `pd.read_csv("data/raw` to `pd.read_csv("../data/raw`

**Comment by chiragrank** [comment]
@d-sel  Thanks for all these corrections.

**Review by d-sel — APPROVED** [review]

**Pull request merged**
