### PR TITLE
Benefits plot

### PR DESCRIPTION
**Pull request by fatse**

### CODE REVIEW

**Review by d-sel — COMMENTED** [review]
@fatse ,
The plot works for me, no coding issues.

However, after interacting with the plot, I am not sure if it makes sense to drill down by question response as well as country. For instance, you end up with situations like this, which I don't think is the intended result:
Screen Shot 2021-01-22 at 23 27 52
Screen Shot 2021-01-22 at 23 28 09

Perhaps we may want to simplify what we want to show with the plot.

Leaving as a comment for further review by others.

**Comment by chiragrank** [comment]
I agree with simplification and also make sure the questions don't overlap with plot-1 with the similarish information

**Comment by fatse** [comment]
@d-sel  thank you for the review. Regarding your suggestion for simplification, I am afraid that there's no straightforward fix to remove the feature that you mentioned above as that is the default behavior for plotly pie charts. 

@chiragrank the questions don't overlap with the first plot as these are clearly related to responses per country.

**Comment by chiragrank** [comment]
@fatse you are right the plot in its current state does not overlap with plot-1. My comment was more intended of making sure of it as a part of the simplification process

**Comment by fatse** [comment]
@chiragrank I am not sure I understand what you mean by "simplification process". Can you clarify that?

**Comment by chiragrank** [comment]
@fatse  Sure, Sorry for not being more clear on that, and thanks for asking. 
For me, it means three things, what information is conveyed, how is it filtered, and how it is presented.
  
For when simplifying interaction, we can also change the country filter. when doing it could end up similar to plot-1 with responses by gender but then I believe that would not happen as the entire goal of this plot is to have that information by country
Other things I meant the layout, since all the three are horizontally stacked, and they have the same country filter, I was suggesting if they can be grouped.

Having said that, in my opinion, this pull request does not need those changes to be included in this milestone. If there is no objection by @d-sel  and @mikelynch416 , we can merge this

**Pull request merged**
